cu.ViewModels.Lesvoorbeeld/Models/ErrorViewModel.cs
using System;

namespace cu.ViewModels.Lesvoorbeeld.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

cu.ViewModels.Lesvoorbeeld/ViewModels/ChuckNorrisQuoteViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace cu.ViewModels.Lesvoorbeeld.ViewModels
{
    public class ChuckNorrisQuoteViewModel
    {
        public string Value { get; set; }
        public string Icon_url { get; set; }
    }
}

cu.ViewModels.Lesvoorbeeld/ViewModels/DeveloperDropDownViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace cu.ViewModels.Lesvoorbeeld.ViewModels
{
    public class DeveloperDropDownViewModel
    {
        public string Name { get; set; }
        public int Id { get; set; }
    }
}

cu.ViewModels.Lesvoorbeeld/ViewModels/GamesGameInfoViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Wba.Oefening.Games.Core;

namespace cu.ViewModels.Lesvoorbeeld.ViewModels
{
    public class GamesGameInfoViewModel
    {
        public int? Id { get; set; }
        public string Title { get; set; }
        public string Developer { get; set; }
        public int? Rating { get; set; }
        public string ImageName { get; set; }
    }
}

cu.ViewModels.Lesvoorbeeld/ViewModels/GamesGetGamesViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace cu.ViewModels.Lesvoorbeeld.ViewModels
{
    public class GamesGetGamesViewModel
    {
        public IEnumerable<GamesGameInfoViewModel> Games { get; set; }
        

    }
}

cu.ViewModels.Lesvoorbeeld/ViewModels/LinkViewComponentViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace cu.ViewModels.Lesvoorbeeld.ViewModels
{
    public class LinkViewComponentViewModel
    {
        public string Url { get; set; }
        public string Name { get; set; }
    }
}

cu.ViewModels.Lesvoorbeeld/Controllers/GamesController.cs
using cu.ViewModels.Lesvoorbeeld.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Wba.Oefening.Games.Core;

namespace cu.ViewModels.Lesvoorbeeld.Controllers
{
    public class GamesController : Controller
    {
        private readonly GameRepository _gameRepository;

        public GamesController()
        {
            _gameRepository = new GameRepository();
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult GetGames()
        {
            //declare view model
            GamesGetGamesViewModel gamesGetGamesViewModel
                = new GamesGetGamesViewModel();
            //get the games from the repo
            gamesGetGamesViewModel.Games = new List<GamesGameInfoViewModel>();
            //get games from repo/database
            //using select method
            gamesGetGamesViewModel.Games=
                _gameRepository.GetGames().Select(g => new GamesGameInfoViewModel
            {
                Id = g?.Id ?? 0,
                Title = g?.Title ?? "<NoTitle>",
                ImageName = g?.ImageName ?? "..."
            }
            );
            
            //foreach (var game in _gameRepository.GetGames())
            //{
            //    gamesGetGamesViewModel.Games.Add(
            //        //add a gamesGameInfoViewModel
            //        new GamesGameInfoViewModel
            //        {
            //            Id = game?.Id ??0,
            //            Title = game?.Title ?? "<NoTitle>"
            //        }
            //        );
            //}
            ViewBag.PageTitle = "Our Games";
            
            //send to the view
            return View(gamesGetGamesViewModel);
        }

        public IActionResult GameInfo(int id)
        {
            //declare the model
            GamesGameInfoViewModel gamesGameInfoViewModel
                = new GamesGameInfoViewModel();
            //get the game by id
            var game = _gameRepository.GetGames()
                .FirstOrDefault(g => g.Id == id);
            //fill the model
            gamesGameInfoViewModel.Id = game?.Id ?? 0;
            gamesGameInfoViewModel.Title = game?.Title ?? "<NoName>";
            gamesGameInfoViewModel.ImageName = game?.ImageName ?? "<NoName>";
            gamesGameInfoViewModel.Rating = game?.Rating ?? 0;
            gamesGameInfoViewModel.Developer = game?.Developer?.Name ?? "<NoDeveloper>";
            //pass to view 
            return View(gamesGameInfoViewModel);
        }
    }
}

cu.ViewModels.Lesvoorbeeld/Controllers/HomeController.cs
using cu.ViewModels.Lesvoorbeeld.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace cu.ViewModels.Lesvoorbeeld.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

cu.ViewModels.Lesvoorbeeld/ViewComponents/DeveloperDropDownViewComponent.cs
using cu.ViewModels.Lesvoorbeeld.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Wba.Oefening.Games.Core;

namespace cu.ViewModels.Lesvoorbeeld.ViewComponents
{
    [ViewComponent(Name = "DeveloperDropDown")]
    public class DeveloperDropDownViewComponent : ViewComponent
    {
        private readonly DeveloperRepository _developerRepository
            = new DeveloperRepository();
        public IViewComponentResult Invoke()
        {
            //declare the viewmodel and add developers
            IEnumerable<DeveloperDropDownViewModel>
                developerDropDownViewModel = _developerRepository
                .GetDevelopers()
                .Select(d => new DeveloperDropDownViewModel
                {
                    Id = d?.Id ?? 0,
                    Name = d?.Name ?? "<NoName>"
                });
            //pass the to the viewmodel
            return View(developerDropDownViewModel);
        }

    }
}

cu.ViewModels.Lesvoorbeeld/ViewComponents/LinksViewComponent.cs
using cu.ViewModels.Lesvoorbeeld.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace cu.ViewModels.Lesvoorbeeld.ViewComponents
{
    [ViewComponent(Name = "LinksComponent")]
    public class LinksViewComponent : ViewComponent
    {
        
        private readonly List<LinkViewComponentViewModel>
            _linksViewComponentViewModel = new List<LinkViewComponentViewModel>();

      
        public IViewComponentResult Invoke()
        {
            _linksViewComponentViewModel.Add(new LinkViewComponentViewModel
            {
                Url = "http://www.gazetta.it",
                Name = "Gazzeta"
            });
            _linksViewComponentViewModel.Add(new LinkViewComponentViewModel
            {
                Url = "http://www.github.com",
                Name = "Github"
            });
            return View(_linksViewComponentViewModel);
        }
    }
}

cu.ViewModels.Lesvoorbeeld/Views/Games/GameInfo.cshtml
@model GamesGameInfoViewModel


<h1>Game Info</h1>
<div class="card mx-auto" style="width: 18rem;">
    <partial name="_gameCardPartial" model="@Model" />
    <div class="card-footer">
        <partial name="_ratingStarPartial" model="@Model.Rating" />
    </div>
    <a asp-controller="Games"
       asp-action="GetGames" class="btn btn-primary w-25 m-1">Back</a>
</div>

cu.ViewModels.Lesvoorbeeld/Views/Games/GetGames.cshtml
@model GamesGetGamesViewModel


<h1>@ViewBag.PageTitle</h1>

<div class="row">
    @foreach (var game in Model.Games)
    {
        <div class="card col-3 m-1" style="width: 18rem;">
            @*call partial view*@
            <partial name="_gameCardPartial" model="@game" />
            <a asp-controller="Games"
               asp-action="GameInfo"
               asp-route-id="@game.Id" class="btn btn-primary">Info</a>
        </div>
    }
</div>

cu.ViewModels.Lesvoorbeeld/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

cu.ViewModels.Lesvoorbeeld/Views/Shared/Components/ChuckNorrisQuote/Default.cshtml
@model ChuckNorrisQuoteViewModel

    <div class="alert alert-primary" role="alert">
        <img src="@Model.Icon_url" />
        <p class="text-info">@Model.Value</p>
    </div>

cu.ViewModels.Lesvoorbeeld/Views/Shared/Components/DeveloperDropDown/Default.cshtml
@model IEnumerable<DeveloperDropDownViewModel>
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Developers
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            @foreach (var developer in Model)
            {
                <a class="dropdown-item"
                   asp-controller="Developers"
                   asp-action="ShowGames"
                   asp-route-id="@developer.Id"
                   >@developer.Name</a>
            }
        </div>
    </li>

cu.ViewModels.Lesvoorbeeld/Views/Shared/Components/LinksComponent/Default.cshtml
@model IEnumerable<LinkViewComponentViewModel>


<h1>Some cool links</h1>
@foreach(var link in Model)
{ 
    <a class="nav-link" href="@link.Url">@link.Name</a>
}

cu.ViewModels.Lesvoorbeeld/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>My Page Title</title>

    <link rel="icon" href="/favicon.ico">
    <link rel="canonical" href="https://mysite.com/mypage">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <!--tips: to change the nav placement use .fixed-top,.fixed-bottom,.sticky-top -->
        <a class="navbar-brand" href="#">My Brand</a>
        <!-- <a class="navbar-brand" href="#">
          <img src="..." class="d-inline-block align-top" width="30" height="30" alt="...">
          My Brand</a> -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" 
                       asp-controller="Games"
                       asp-action="GetGames">Games <span class="sr-only">(current)</span></a>
                </li>
                @* call the viewcomponent developerdropdown *@
                @await Component.InvokeAsync("DeveloperDropDown") 
            </ul>

        </div>
    </nav>

    <main role="main" class="container">
        <div class="starter-template">
            @RenderBody()
        </div>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

cu.ViewModels.Lesvoorbeeld/Views/Shared/_gameCardPartial.cshtml
@model GamesGameInfoViewModel
<!--tips: add .text-center,.text-right to the .card to change card text alignment-->

<img asp-append-version="true" src="/img/@Model.ImageName" class="card-img-top mx-auto m-1" alt="...">
<div class="card-body">
    <h5 class="card-title">@Model.Title</h5>
    <h6 class="card-subtitle mb-2 text-muted">@Model.Developer</h6>
</div>

cu.ViewModels.Lesvoorbeeld/Views/Shared/_ratingStarPartial.cshtml
@model int
@for (int i = 1; i <= 5; i++)
{
    if (i <= Model)
    {
        <span class="icon-star"></span>
    }
    else
    {
        <span class="icon-star-empty"></span>
    }
}